-- MySQL Script generated by MySQL Workbench
-- Mon May 15 13:43:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenda_atividades
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda_atividades
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda_atividades` DEFAULT CHARACTER SET utf8 ;
USE `agenda_atividades` ;

-- -----------------------------------------------------
-- Table `agenda_atividades`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `imagem` VARCHAR(45) NULL,
  `nivel` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_atividades`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `nivel` INT NULL,
  `xp` INT NULL,
  `avatar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_avatares1_idx` (`avatar_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_avatares1`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `agenda_atividades`.`avatar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_atividades`.`tipo_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`tipo_atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `geral` TINYINT NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_atividade_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_atividade_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agenda_atividades`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_atividades`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `descricao` TEXT NULL,
  `data_criacao` DATETIME NULL DEFAULT NOW(),
  `data_limite` DATETIME NULL,
  `data_primeira_completacao` DATETIME NULL,
  `horario_repeticao` TIME NULL,
  `repete` TINYINT NULL,
  `usuario_id` INT NOT NULL,
  `tipo_atividade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_atividades_tipo_atividade1_idx` (`tipo_atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividades_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agenda_atividades`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_tipo_atividade1`
    FOREIGN KEY (`tipo_atividade_id`)
    REFERENCES `agenda_atividades`.`tipo_atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_atividades`.`atividade_completacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`atividade_completacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  `data_completacao` DATETIME NULL,
  `atividade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_completacao_atividades1_idx` (`atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividades_completacao_atividades1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `agenda_atividades`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_atividades`.`atividade_repete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`atividade_repete` (
  `atividade_id` INT NOT NULL,
  `dia_semana` INT NULL,
  INDEX `fk_table1_atividades1_idx` (`atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_atividades1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `agenda_atividades`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_atividades`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_atividades`.`token` (
  `usuario_id` INT NOT NULL,
  `token` VARCHAR(80) NULL,
  `data_limite` DATETIME NULL,
  INDEX `fk_token_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_token_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agenda_atividades`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
